{{- if .Capabilities.APIVersions.Has "apps/v1" -}}
apiVersion: apps/v1
{{ else }}
apiVersion: extensions/v1beta1
{{- end -}}
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    namespace: {{ .Release.Namespace }}
    chartfullname: {{ .Chart.Name}}-{{ .Chart.Version }}
    chartname: {{ .Chart.Name }}
    chartversion: {{ .Chart.Version }}
    version: {{ quote .Values.version }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tags }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
