{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Files.Get .Values.tls.cretpath | b64enc }}
  tls.key: {{ .Files.Get .Values.tls.keypath | b64enc }}

{{- end }}
