apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerPort }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodeport }}
    nodePort: {{ .Values.service.nodeport }}
    {{- end }}
